1. What does Pandas stand for?
- Panel Data
- Python Data Analysis

2. What are the 2 collections used in Pandas?

3. Name 4 things Pandas can do for us.

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

5. What is a CSV?

6. When cleaning data what values do we not like in our data?

In [1]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

# Create an array 
original_array = np.arange(12)

# Reshape array 
reshaped_array = original_array.reshape(2, 3, 2)
print(reshaped_array)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [18]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

new_array = np.linspace(0,20,6)
print(new_array)

[ 0.  4.  8. 12. 16. 20.]


In [19]:
# 9. Make a Deep Copy of the above array

import copy

deep = copy.deepcopy(new_array)

In [10]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...

        ([[25, 16]])
        ([[11, 2], [13, 4]])
        ([[7, 81], [5, 6], [11, 12]])

IndentationError: unexpected indent (3026162728.py, line 3)

In [11]:
arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis=0)

In [14]:
# 11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)

In [17]:
# 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

var1,var2,var3,var4 = array

print(var1)
print(var2)

NameError: name 'array' is not defined

In [ ]:
# 13. Combined and sort the following arrays into one called 'comboArray' ...
    one = ([10, 11, 12, 13, 14, 15, 16, 17])
    two = ([20, 21, 22, 23, 24, 25, 26, 27])
    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# 14. Take 'comboArray' and perform the following slicing activities:

print sec1 - the 2nd element
print sec2 - all elements from the 3rd element to the last
print sec3 - all elements from the 4th to the 14th elements
print sec4 - the last 6 elements
print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print sec6 - from #20 every even element to the end
print sec7 - from the last element moving forward, every 5th element.

In [ ]:
# 15. Using Series, create a DataFrame that looks like this:

Ingredients	Quantity    Unit
Flour	    4	        cups
Milk	    1	        cup
Eggs	    2	        large
Spam	    1	        can
Name: Dinner, dtype: object

In [ ]:
# 16. Take this data and create a DataFrame named studentData

    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

In [ ]:
# 17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [ ]:
# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [ ]:
# 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
    df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [ ]:
# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.