1. What does Pandas stand for?
- _Panel Data_
- _Python Data Analysis_

2. What are the 2 collections used in Pandas?
- _Series_
- _Data Frames_

3. Name 4 things Pandas can do for us.
    1. _Data Cleansing_
    2. _Data Normalization_
    3. _Data Visualization_
    4. _Data Inspection_

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
<br>
inplace = True

5. What is a CSV?
_File that uses commas to separate values. Comma-separated values = CSV._

6. When cleaning data what values do we not like in our data?
_Null values_


In [72]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np
import pandas as pd

# Create first array 
first_array = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(first_array)

# Reshape array 
reshaped_array = array.reshape(2, 3, 2)
print(reshaped_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [73]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

new_array = np.linspace(0,20,6)
print(new_array)

[ 0.  4.  8. 12. 16. 20.]


In [74]:
# 9. Make a Deep Copy of the above array

import copy

deep = copy.deepcopy(new_array)
print(deep)

[ 0.  4.  8. 12. 16. 20.]


In [75]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...

# ([[25, 16]])
# ([[11, 2], [13, 4]])
# ([[7, 81], [5, 6], [11, 12]])

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC))
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [76]:
# 11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [77]:
# 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

var1,var2,var3,var4 = first_array

print(var1)
print(var2)
print(var3)
print(var4)

#Re-do.

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [78]:
# 13. Combined and sort the following arrays into one called 'comboArray' ...
# one = ([10, 11, 12, 13, 14, 15, 16, 17])
# two = ([20, 21, 22, 23, 24, 25, 26, 27])
# three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [79]:
# 14. Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
# print sec2 - all elements from the 3rd element to the last
# print sec3 - all elements from the 4th to the 14th elements
# print sec4 - the last 6 elements
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
# print sec6 - from #20 every even element to the end
# print sec7 - from the last element moving forward, every 5th element.

sec1 = comboArray[1]  
print("sec1:", sec1)

sec2 = comboArray[2:]  
print("sec2:", sec2)

sec3 = comboArray[3:14]
print("sec3:", sec3)

sec4 = comboArray[-6:]
print("sec4:", sec4)

sec5 = comboArray[-24:-10]  
print("sec5:", sec5)

sec6 = comboArray[-8::2] 
print("sec6:", sec6)

sec7 = comboArray[-1::-5]  
print("sec7:", sec7)

sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6: [20 22 24 26]
sec7: [27 22 15 10  3]


In [80]:
# 15. Using Series, create a DataFrame that looks like this:

#Ingredients	Quantity    Unit
#Flour	    4	        cups
#Milk	    1	        cup
#Eggs	    2	        large
#Spam	    1	        can
#Name: Dinner, dtype: object

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'])
quantity = pd.Series([4, 1, 2, 1])
unit = pd.Series(['cups', 'cup', 'large', 'can'])

dinner_dataframe = pd.DataFrame({'Ingredients': ingredients, 'Quantity': quantity, 'Unit': unit})
dinner_dataframe

Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [81]:
# 16. Take this data and create a DataFrame named studentData

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [82]:
# 17. Add a new column to the DataFrame with the following desserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)

desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['desserts'] = desserts
print(studentData)

# desert = sand 
# dessert = sweet dish

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [83]:
# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by= ['Name', 'address'], inplace=True)
studentData

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [84]:
# 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
# df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')
animals = pd.read_csv('cows_and_goats.csv')
animals

Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19

In [85]:
# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

vegetables = pd.DataFrame({"vegetables": ["onions", "broccoli", "zucchini", "corn"]})
vegetables.to_csv('vegetables.csv')
df = pd.read_csv('vegetables.csv')
print(df)

print("\n")

df["vegetables"] = ["apple", "orange", "banana", "pineapple"]
df.to_csv("fruits.csv",index=False)
updated_df = pd.read_csv("fruits.csv")
updated_df

   Unnamed: 0 vegetables
0           0     onions
1           1   broccoli
2           2   zucchini
3           3       corn




Unnamed: 0 vegetables
0           0      apple
1           1     orange
2           2     banana
3           3  pineapple